[build-system]
requires = ["setuptools~=77.0"]
build-backend = "setuptools.build_meta"

[project]
name         = "smartverse-frontend"
version      = "20250424.0"
license      = "Apache-2.0"
license-files = ["LICENSE*"]
description  = "The Smartverse frontend"
readme       = "README.md"
authors      = [
    {name = "The Smartverse Authors", email = "hello@Smartverse.io"}
]
requires-python = ">=3.13.0"


[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["hass_frontend*"]
